[project]
name = "SavingFromFormData"

[[services]]
name = "SavingFromFormData-service"
type = "web"
build = "."
envVars = [
  dotenv = "hakr",
]
resources = {
  cpu = "free"
}
ports = [
  { port = 5000, protocol = "TCP" }
]
routes = [
  { path = "/*" }
]
